FROM golang:1.10 AS builder

# Download and install the latest release of dep
ADD https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 /usr/bin/dep
RUN chmod +x /usr/bin/dep

RUN curl -fLo air https://git.io/linux_air
RUN mv air /usr/bin/air && chmod +x /usr/bin/air

WORKDIR $GOPATH/src/app

COPY Gopkg.toml Gopkg.lock ./
RUN dep ensure --vendor-only

COPY . ./

CMD ["/usr/bin/air"]