version: "3.7"
services:
  sonar:
    image: sonarqube:8.2-community
    volumes:
      - "./sonar/sonar.properties:/opt/sonarqube/conf/sonar.properties"
      - "./tmp/data:/opt/sonarqube/data"
    ports:
      - "9000:9000"
      - "9092:9092"
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "http://0.0.0.0:9000"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  node_app:
    image: sonnar-scanner:latest
    restart: on-failure
    volumes:
      - "./node_app:/app"
    depends_on:
      - sonar

  go_app:
    image: sonnar-scanner:latest
    restart: on-failure
    volumes:
      - "./go_app:/app"
    depends_on:
      - sonar

  
